### ISSUE TITLE
Windows 10 will claim sgminer has stopped responding and end the process

### ISSUE THREAD

**Issue by Velkas** [lenis0012/sgminer-gm#3]
Running Windows 10, the 5.6.0 Allium build with minimal options (algo option, with testnet pool and wallet) will start up like normal, but as soon as it tries to initialize my Vega64, windows will pop up a window saying sgminer has stopped working and that it is ending the process for me. I had no issues with 5.5.5 on scrypt-n.

[image of what happens](https://i.imgur.com/yWGy95c.png)
and my bat file: 
> sgminer --algorithm allium -I 14 -o stratum+tcp://testnet.garlic-factory.fun:3333 -u n4hC3H8nWVPm4YSEgi5BtQBFtLjDFfDjXf -p x

**Comment by namsur1234** [comment]
Similar to my issue. Try removing intensity setting and see if it runs. I also read something about it crashing if you either didn't have your path set for your batch file properties or put the full path in the batch file, you might give that a shot. The miner does seem to be very picky about what is/isn't run.

**Comment by Velkas** [comment]
I tried removing intensity to the same effect. I'll try the pathway issue now.

**Comment by Velkas** [comment]
Ok updated the bat to use the absolute path, but no difference. It still crashes after starting up properly. To clarify, the bat is in the same folder as the miner. And the miner IS starting up, it's just crashing at some point in the initialization.

**Comment by lenis0012** [comment]
@Velkas You closed the issue. Did you find a solution?
